#ifndef ISR80H_H
#define ISR80H_H

enum SystemCommands
{
  SYSTEM_COMMAND1_PRINT = 1,
  SYSTEM_COMMAND2_GETKEY,
  SYSTEM_COMMAND3_SLEEP,
  SYSTEM_COMMAND4_OPEN,
  SYSTEM_COMMAND5_READ,
  SYSTEM_COMMAND6_SBRK,
  SYSTEM_COMMAND7_CLOSE,
  SYSTEM_COMMAND_WRITE,
  SYSTEM_COMMAND_EXIT,
  SYSTEM_COMMAND_WAIT,
  SYSTEM_COMMAND_EXEC,
  SYSTEM_COMMAND_FSTAT,
  SYSTEM_COMMAND_SET_FOCUS,
};

void isr80h_register_command_call();

#endif