#ifndef CONFIG_H
#define CONFIG_H

#define MYOS_KERNEL_CODE_SELECTOR 0x08
#define MYOS_KERNEL_DATA_SELECTOR 0x10
#define MYOS_TOTAL_GDT_SEGMENTS 6

//for parser
#define MYOS_MAX_PATH_LENGTH 108


#define MYOS_TOTAL_INTERRUPTS 512

#define MYOS_MAX_FILESYSTEMS 12
#define MYOS_MAX_FILE_DESCRIPTORS 512

//100MB
//1mb = 1024 kb 
//100MB = 100 × 1024 × 1024 bytes
#define MYOS_HEAP_SIZE_BYTES 104857600
#define MYOS_HEAP_BLOCK_SIZE 4096

#define HEAP_ADDRESS 0x01000000 // Heap starts at 16MB
#define HEAP_TABLE_ADDRESS 0x00007E00 // Heap table location

#define MYOS_SECTOR_SIZE 512

#define MYOS_PROGRAM_VIRTUAL_ADDRESS 0x400000

#define MYOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define MYOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define MYOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END MYOS_PROGRAM_VIRTUAL_ADDRESS_START - MYOS_USER_PROGRAM_STACK_SIZE //because stack grows downwards

#define MYOS_USER_DATA_SEGMENT 0x23
#define MYOS_USER_CODE_SEGMENT 0x1b

//for process
#define MYOS_MAX_ALLOCATIONS 1024
#define MYOS_MAX_PROCESSES 12

//for isr80h commands interupt system routine
#define MYOS_MAX_ISR80H_COMMANDS 1024

#endif